### ISSUE TITLE
page level styles

### ISSUE THREAD

**Issue by cjessett** [Lamalord/prj-rev-bwfs-dasmoto#3]
(Important) [Here](https://github.com/Lamalord/prj-rev-bwfs-dasmoto/blob/b4bb457b02657ef800f14eb7dbac2f13f5ec065e/Dasmotos_Arts_and_Crafts/resources/style.css#L6-L8) you should move this to the top of the file. In general, style declarations are made with the parent elements at the top and child elements below them. Also, page level styles are conventional made on the `body` element instead of the `html` element since the `body` is what is actually displayed.

**Comment by Lamalord** [comment]
fixed
