### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by cjessett** [Lamalord/prj-rev-bwfs-dasmoto#4]
(Meets Expectations) Overall, nice work.

Remember to put all images in a folder titled `images`. Also, remember to declare page level styles at the top of your css file and that they can be declared on the `body` element.

Again, excellent use of the `class` attribute to apply multi-use styles, your code is clean and easy to follow, nice job!

**Comment by Lamalord** [comment]
cheers.
Thank you.!
